sudo: required
services:
  - docker

before_install:
  - docker build -t iamsmug/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true iamsmug/react-test npm test

after_success:
  - docker build -t iamsmug/multi-client ./client
  - docker build -t iamsmug/multi-nginx ./nginx
  - docker build -t iamsmug/multi-server ./server
  - docker build -t iamsmug/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push iamsmug/multi-client
  - docker push iamsmug/multi-nginx
  - docker push iamsmug/multi-server
  - docker push iamsmug/multi-worker

deploy:
  provider: elastibeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-723762033082
  bucket_path: docker-multi
  on:
    brach: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
